### ISSUE TITLE
ax_check_gnu_make.m4 should be included

### ISSUE THREAD

**Issue by atsampson** [flatpak/xdg-dbus-proxy#17]
#9 made xdg-dbus-proxy bundle a copy of ax_code_coverage.m4 from autoconf-archive. However, since AX_CODE_COVERAGE uses AX_CHECK_GNU_MAKE internally, this means autoreconf fails on xdg-dbus-proxy 0.1.2 if you don't have autoconf-archive installed:

```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /gar/bin/autoconf --force
configure.ac:51: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /gar/bin/autoconf failed with exit status: 1
```

Adding ax_check_gnu_make.m4 to the bundled files fixes this.

**Comment by ahimta** [comment]
I had the same issue and installing `autoconf-archive` fixed it indeed. This is important to fix especially since that searching for the error-message doesn't seem to include any viable solutions. @atsampson it would be great if you could provide a PR and hopefully it will get merged before others come across it and spend the time to fix it or give up trying.
